### ISSUE TITLE
Nodes get repeated in rc.xml

### ISSUE THREAD

**Issue by 01micko** [labwc/labwc-tweaks#11]
@johanmalm  I tested 162f5bc before approving but there is a bug apparent. (Note to self, don't test stuff when tired!)

If a node exists it doesn't seem to be read and the gui shows a default, `0` in the case of `cornerRadius` and nothing shows in the gui.

If the entry is selected and changed the node is repeated in the `rc.xml`

This is a snippet of my  `rc.xml` after changing.

```xml
  <theme>
    <name>Stardust_dark_mouse</name>
    <cornerRadius>3</cornerRadius>
    <cornerradius>3</cornerradius>
  </theme>
...
  <libinput>
    <device category="default">
      <naturalScroll>yes</naturalScroll>
      <leftHanded/>
      <pointerSpeed/>
      <naturalscroll>yes</naturalscroll>
    </device>
  </libinput>
```

Openbox theme seems unaffected.

**Comment by johanmalm** [comment]
Any better now?

**Comment by 01micko** [comment]
Yes :smile:
