### ISSUE TITLE
include a license

### ISSUE THREAD

**Issue by 10leej** [labwc/labwc-tweaks#14]
I want to write a gentoo ebuild abd publish it, but you need to include a license file witht he repo. I take it this was forgotten.

**Comment by 01micko** [comment]
@johanmalm GPLv2 like labwc?

Thanks @10leej

**Comment by johanmalm** [comment]
It's called `gpl-2.0.txt`
https://github.com/labwc/labwc-tweaks/blob/253667cb776cd74d9f39067721b1bf5f729c7b45/gpl-2.0.txt#L1

Suspect I just did a `wget https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt`

I'll rename it to `LICENSE`
