### ISSUE TITLE
tweaks messes up "keyboard" section in rc.xml

### ISSUE THREAD

**Issue by stefonarch** [labwc/labwc-tweaks#15]
Only open, update and quit and the file changes like that:
![screen_area_mer_23:15:29_](https://github.com/labwc/labwc-tweaks/assets/10681413/ee2159f2-7989-4aba-a93c-e9ee88cfc49f)

All whitespaces removed. This didn't happen earlier, so I think there has to be something which triggers that in `rc.xml` but didn't find anything. Can share the file if necessary.

**Comment by johanmalm** [comment]
Yes, if you could share the file, that would be useful.

**Comment by stefonarch** [comment]
[rc.xml.txt](https://github.com/labwc/labwc-tweaks/files/11684222/rc.xml.txt)

**Comment by stefonarch** [comment]
Playing with `obconf-qt` modifying` labwc/rc.xml` I noticed it does just the same, (settings like fonts, themes, desktops, window are working, it just should be cleaned from X11 code). Staring again at the file...

**Comment by johanmalm** [comment]
You have a dot/period at the start of one of the `<keybind>` lines.

```
163c163
<     <keybind key="W-KP_3"><action name="SnapToRegion" region="bottom-right"/></keybind>
---
> .   <keybind key="W-KP_3"><action name="SnapToRegion" region="bottom-right"/></keybind>
```

If you remove the dot it works fine.

**Comment by stefonarch** [comment]
> If you remove the dot it works fine.

My monitor was dirty ;) I thought the issue  was more up the file, fed it also in an online validator which didn't complain. Thanks and sorry for the noise. Looks like this dot doesn't invalidate the syntax, obconf-qt spites a warning if it's wrong.

>I've had a quick play with obconf-qt...

I played quite a lot [here](https://github.com/stefonarch/labwc-conf) to test, but probably writing something in qt from scratch or developing more labwc-tweaks is the better way. It's to much depending on openbox for config paths and tools, on wayland it segfaults because of those openbox dependencies. 

Nice would be 4 top tabs for the 4 config files and a good grouping for `rc.xml` tab, but it's quite much work I guess. Annyway, enjoying much labwc now.

**Comment by stefonarch** [comment]
> I've had a quick play with `obconf-qt`.

FYI: https://github.com/lxqt/obconf-qt/issues/217
