### ISSUE TITLE
Segmentation Fault.

### ISSUE THREAD

**Issue by ahmadraniri1994** [labwc/labwc-tweaks#2]
Compiled it some days ago and still find it gets "Segmentation fault".
OS : Archlinux 
[labwc-tweaks-gdb-bt.txt](https://github.com/labwc/labwc-tweaks/files/7657221/labwc-tweaks-gdb-bt.txt)
[labwc-tweaks-gdb-run.txt](https://github.com/labwc/labwc-tweaks/files/7657222/labwc-tweaks-gdb-run.txt)
[labwc-tweaks-WAYLAND_DEBUG.txt](https://github.com/labwc/labwc-tweaks/files/7657223/labwc-tweaks-WAYLAND_DEBUG.txt)

**Comment by 01micko** [comment]
I know why this happens and can reproduce but not sure of the best approach to fix it.

If you have this in your `rc.xml` : 

```xml
<naturalScroll></naturalScroll>
```

that is, unset, then we get the segfault but if it is set to either yes or no then it works as expected.

Strangely, if there is no `<libinput>` block then the program runs fine but obviously does nothing if 'natural scrolling' is set in the GUI.

Aditionally, if we have other entries that are unset and 'natural scroll' is set in `rc.xml` these other entries get changed thus: (example)

```xml
  <libinput>
    <device category="default">
      <naturalScroll>no</naturalScroll>
      <leftHanded/> <!-- here -->
      <pointerSpeed/> <!-- and here -->
    </device>
  </libinput>

``` 

The upshot is that we need more robust parsing of `rc.xml` and better handling of other unset entries.

**Comment by johanmalm** [comment]
Thanks for analyzing this. Fix now pushed.

Not sure how to prevent `<foo></foo>` becoming `<foo />` on `xmlFileWrite()`
There might be some option in https://gnome.pages.gitlab.gnome.org/libxml2/devhelp/libxml2-tree.html#xmlSaveFile or similar, but I can't find anything obvious.
I'm happy to except behavior as is - but welcome help if anyone is willing.

**Comment by johanmalm** [comment]
![20220424_09h44m00s_grim](https://user-images.githubusercontent.com/6955353/164969689-c2115c36-ad38-454c-b752-0356766156fb.png)

Scrot from this morning
