### ISSUE TITLE
Menu entry is shown under "System" eventually.

### ISSUE THREAD

**Issue by stefonarch** [labwc/labwc-tweaks#53]
In LXQt ConfigurationCenter it's the only settings tool which shows up under "System":

![immagine](https://github.com/labwc/labwc-tweaks/assets/10681413/df99c91c-60b8-4203-a1b3-389a514b5233)

Other menus in LXQt show it under "Settings".

Comparing to sddm-conf which uses `Categories=Qt;Settings;DesktopSettings;` while labwc-tweaks uses `Categories=Settings;System;` 

Not sure if "System" category really applies to it.

**Comment by redtide** [comment]
Looking at Freedesktop specification a system application should be something that controls/monitors the system. so this is not really the case, which is actually a settings application.
I think the sddm-conf category list should be good for this as well.
