### ISSUE TITLE
Closing (without applying) apply changes and modifies the environment file

### ISSUE THREAD

**Issue by Bluey26** [labwc/labwc-tweaks#75]
Hello, i just cloned last AUR `labwc-tweaks-git` package from archlinux arch user repository (https://aur.archlinux.org/packages/labwc-tweaks-git)  and i have the following issues:

~~For some reason labwc-tweaks does not recognize my other keyboard layouts, but only 1 (it may be related to the presence of keyboard variants and '()' in their names). It only shows the last one in the options( see attached photo).~~

In the other side, opening labwc-tweaks and closing the program without using 'Apply' button first seems to overwrite the options(it changes the layouts from my 3 original ones to only greek, and produces the 1st problem i report above).

In my `environment` file i have the following:

```
XKB_DEFAULT_OPTIONS=grp:lwin_toggle
XKB_DEFAULT_LAYOUT=latam(deadtilde),ru(phonetic),gr
```

Which is changed to the following after closing the labwc-tweaks program:

```
XKB_DEFAULT_OPTIONS=grp:lwin_toggle
XKB_DEFAULT_LAYOUT=gr
```

I dont know what is happening, i was just changing the labwc-theme and then suddenly i ended up with only 1 keyboard layout. I always can change the labwc-theme using the `.xml` file but the tweaks GUI is always better.

Information:
```
OS: Archlinux (updated)
WM: labwc 0.7.2
DE: LXQt 2.0 + labwc
```

Complete `environment` file:

[environment-lxqt-labwc.txt](https://github.com/labwc/labwc-tweaks/files/15409058/environment-lxqt-labwc.txt)

![tweaks](https://github.com/labwc/labwc-tweaks/assets/143142826/dc15fba6-b99a-4446-88cb-bd84650f3860)

Setting back the layouts using the original lines + `labwc -r` reverts is back.

---

## **Update:**

As it was suggested by another lxqt+labwc user, the problem seems to be around the keyboard variants (variant).

If i set this up (notice the lack of parentheses or round brackets after the keyboard layout) :

`XKB_DEFAULT_LAYOUT=latam,ru,gr`

in `environment` (i run `labwc -r` ) and then in open labwc-tweaks, the three keyboard layouts are present (in their default variants, or something as no variant).
If i click the 'Close' button, i end up with the three keyboard layouts (the Close button still modified the environment file even when i do not click the Apply button).

~~This looks like as: labwc-tweaks still not supporting keyboard variants?~~

This is how the labwc-tweaks GUI looks like after removing the keyboard variants:~~

![novariants](https://github.com/labwc/labwc-tweaks/assets/143142826/eca156a0-12f8-4a4c-8408-0c4c87ecc64a)

---

PS: I know the file is changed (even in the 'update' case) because `Featherpad` (text editor) shows a warning message upon focusing the` environment ` file (this happens when the file was loaded and then it changed).

![featherpad-warning](https://github.com/labwc/labwc-tweaks/assets/143142826/197551e4-1f77-488b-94d6-be5b12e12c04)

---

## Update2 

The problem with the keyboard layouts is solved by specifying the keyboard variants using:

```
XKB_DEFAULT_VARIANT=deadtilde,phonetic,
XKB_DEFAULT_LAYOUT=latam,ru,gr
```
_A comma (,) was added in XKB_DEFAULT_VARIANT to follow the example given in the comment_

Now, labwc-tweaks recognizes the 3 keyboard layouts, and changing the theme will not affect my keyboard layout (because it is recognized properly).

The 'Close' issue is still around so i will keep the issue open.

**Comment by Consolatis** [comment]
> XKB_DEFAULT_VARIANT=deadtilde,phonetic
> XKB_DEFAULT_LAYOUT=latam,ru,gr

https://xkbcommon.org/doc/current/structxkb__rule__names.html#a758e1865c002d8f4fb59b2e3dda83b66 mentions:
> A comma separated list of variants, one per layout, which may modify or augment the respective layout in various ways.
>
>Generally, should either be empty or have the same number of values as the number of layouts. You may use empty values as in "intl,,neo".
>
>If NULL or the empty string "", and a default value is also used for the layout, a default value is used. Otherwise no variant is used. If the XKB_DEFAULT_VARIANT environment variable is set, it is used as the default. Otherwise the system default is used.

Thus the example should likely include an empty entry somewhere so it matches  the count of entries in `XKB_DEFAULT_LAYOUT`.

**Comment by johanmalm** [comment]
Suggestions on how to do the UI welcome.

@Bluey26 - if you're looking to code this let me know, otherwise I'll take a look at it.

**Comment by johanmalm** [comment]
Testing welcome. 

- [ ] Handling of `XKB_DEFAULT_LAYOUT` outstanding. Will probably do a separate issue for this.
- [ ] "In the other side, opening labwc-tweaks and closing the program without using 'Apply' button first seems to overwrite the options" - not look at this yet.

**Comment by Bluey26** [comment]
> Testing welcome.
> 
>     * [ ]  Handling of `XKB_DEFAULT_LAYOUT` outstanding. Will probably do a separate issue for this.
> 
>     * [ ]  "In the other side, opening labwc-tweaks and closing the program without using 'Apply' button first seems to overwrite the options" - not look at this yet.

It seems to work in here :D 

What i did:

- Cloned the handle-variants branch using the labwc-git PKGBUILD.

- Changed my `environment` file to test if the program now detects the layouts, with the syntax:

`XKB_DEFAULT_LAYOUT=latam(deadtilde),ru(phonetic),gr`

Then, i compiled and installed the handle-variants branch.
After that, opening the program and going to Language & region shows the 3 layouts.

I also tested the following: i deleted the 3 layouts, since i noticed you have added the variants in the UI (thanks for this too). I selected again the spanish(deadtile) and russian(phonetic) but not the greek one, and after apllying and closing the program, the `environment` showed the correct info in my side :
`

XKB_DEFAULT_LAYOUT=latam(deadtilde),ru(phonetic)`

This means that the variant part is also working when you add then from zero.

About the 2nd issue:

>"In the other side, opening labwc-tweaks and closing the program without using 'Apply' button first seems to overwrite the options" - not look at this yet.

I just discovered that this happens when i press 'Close', but it does not happen to me when i use the X at the top(window title). This was discovered before installing the new branch, and i also verified it with the new one (The problem should be around the Close button, that somehows is also applying the changes).

**Comment by johanmalm** [comment]
See #79  - this now lets you close without applying by pressing close button.

**Comment by Bluey26** [comment]
> See #79 - this now lets you close without applying by pressing close button.

Indeed, now pressing 'Close' does not makes changes in the file(as clicking the X in the menu title).

Thank you very much :D

**Comment by johanmalm** [comment]
Thanks for testing. 

The final piece of the jigsaw is in #80 if you fancy more testing. Otherwise I'll merge it later anyway.

**Comment by Bluey26** [comment]
> Thanks for testing.
> 
> The final piece of the jigsaw is in #80 if you fancy more testing. Otherwise I'll merge it later anyway.

I am not sure what is the change in here, but by the name of the branch i tested the following:

`latam(deadtilde) --> latam` 
^ This should show the default latam layout inside the options, and it does (it does not show any keyboard variant).

I think the change is more in the code side, but everything seems to work in here

**Comment by johanmalm** [comment]
It makes us cope with 

    XKB_DEFAULT_LAYOUT=latam
    XKB_DEFAULT_VARIANT=deadtilde

...by turning it into:

    XKB_DEFAULT_LAYOUT=latam(deadtilde)
    XKB_DEFAULT_VARIANT=

Comma semarated values are supported too.

**Comment by Bluey26** [comment]
> It makes us cope with
> 
> ```
> XKB_DEFAULT_LAYOUT=latam
> XKB_DEFAULT_VARIANT=deadtilde
> ```
> 
> ...by turning it into:
> 
> ```
> XKB_DEFAULT_LAYOUT=latam(deadtilde)
> XKB_DEFAULT_VARIANT=
> ```
> 
> Comma semarated values are supported too.

Oh, yes. It transforms:

```
XKB_DEFAULT_LAYOUT=latam,ru,gr
XKB_DEFAULT_VARIANT=deadtilde,phonetic,
```

Into:

```
XKB_DEFAULT_LAYOUT=latam(deadtilde),ru(phonetic),gr
XKB_DEFAULT_VARIANT=
```

I dont know if its normal that `XKB_DEFAULT_VARIANT=` was replaced with empty, instead of the variable being deleted, but the change works in here

**Comment by johanmalm** [comment]
Thanks for testing. I'll got for merge.
I'll just leave `XKB_DEFAULT_VARIANT=` set to empty. Just feels better.

**Comment by johanmalm** [comment]
Enough for one night. Thanks for reporting all this.
