### ISSUE TITLE
building error - find-themes.c:53:13: error: 'PATH_MAX' undeclared

### ISSUE THREAD

**Issue by m4lin** [labwc/labwc-tweaks#8]
Hello

trying to build tweaks, but error at ninja -C build, see link 
https://pastebin.com/BHPQQHmb

any suggestion? 

i can build succesfully labwc, system Void Linux.

thanks

Marco

**Comment by johanmalm** [comment]
Just added -s to the killall command too :smile:

**Comment by m4lin** [comment]
Hello 

Thanks!! i confirm it is working building correctly now, and the application works, i am trying to use it, will advise if any issues will arise.

PS. i built also the labwc master with the fix for the issue with Void's killall and confirmed it is all working now!!!

thanks again

Marco

**Comment by m4lin** [comment]
> Just added -s to the killall command too smile

just to mention, after the latest commit and change introduced i do have ninja warning me as per below:

https://pastebin.com/QH3xLXZD

not sure it is important

KR

Marco

**Comment by johanmalm** [comment]
It's probably a musl thing.  Maybe we haven't defined the correct _POSIX_C_SOURCE or something like that.
Would this patch help (i.e. just add the `#define _POSIX_C_SOURCE` line)?

```
diff --git a/src/action.c b/src/action.c
index d9f22eb..aaa91de 100644
--- a/src/action.c
+++ b/src/action.c
@@ -1,4 +1,5 @@
 // SPDX-License-Identifier: GPL-2.0-only
+#define _POSIX_C_SOURCE
 #include <strings.h>
 #include <wlr/util/log.h>
 #include <signal.h>
```

**Comment by m4lin** [comment]
> It's probably a musl thing. Maybe we haven't defined the correct _POSIX_C_SOURCE or something like that. Would this patch help (i.e. just add the `#define _POSIX_C_SOURCE` line)?
> 
> ```
> diff --git a/src/action.c b/src/action.c
> index d9f22eb..aaa91de 100644
> --- a/src/action.c
> +++ b/src/action.c
> @@ -1,4 +1,5 @@
>  // SPDX-License-Identifier: GPL-2.0-only
> +#define _POSIX_C_SOURCE
>  #include <strings.h>
>  #include <wlr/util/log.h>
>  #include <signal.h>
> ```

confirmed this way the warning is gone.
KR

Marco

**Comment by johanmalm** [comment]
Fixed with https://github.com/labwc/labwc/commit/46ee0707901eb30113696dd9240a7ced9eb700a2
Thanks for reporting.
