### ISSUE TITLE
Labwc Tweaks disables keyboard by adding `XKB_DEFAULT_LAYOUT=` to `.config/labwc/environment`

### ISSUE THREAD

**Issue by jjramsey** [labwc/labwc-tweaks#89]
I had a problem where the keyboard stopped working in Labwc -- and *only* Labwc, and it took me a while to figure out that it was related to Labwc Tweaks. Basically, if the keyboard type isn't set in the Labwc Tweaks GUI, then it writes `XKB_DEFAULT_LAYOUT=` (without anything after the `=` sign) to `.config/labwc/environment`. This is what disables the keyboard.

**Comment by anwarsfaizul** [comment]
same issue. had to set a language in labwc to get back my keyboard functions.

**Comment by johanmalm** [comment]
Thanks for reporting. Now fixed in `master`.
